
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/software/cmake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
